name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build and Run Docker
      if: always()
      run: cd ~/actions-runner/_work/codegena/codegena && docker compose down && docker compose up -d
      env:
        GH_CLIENT_ID: ${{ secrets.GH_CLIENT_ID }} 
        GH_CLIENT_SECRET: ${{ secrets.GH_CLIENT_SECRET }} 
        PYTHONDONTWRITEBYTECODE: 1
        DB_PATH: ~/actions-runner/_work/db/codegena

